[package]
name = "try-1"
version = "0.1.0"
authors = ["Abutayar Shaikh <abutayarshaikh@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
